### ISSUE TITLE
quicksettings menu in titlebar looks odd

### ISSUE THREAD

**Issue by dipunm** [akiirui/akwaita-theme#1]
I like this theme because its almost stock, but on my low resolution laptop, it keeps the size of fonts and shell widgets smaller.

That said, there is a bug that has come a while ago and no changes. Here is a screenshot:

![image](https://github.com/akiirui/akwaita-theme/assets/5099980/2af49468-0c91-4dd2-b04e-6fb41f25b387)

**Comment by akiirui** [comment]
So, what version of `gnome-shell` are you using

**Comment by akiirui** [comment]
Now, if you don't use archlinux, you can install a specific version via https://github.com/akiirui/akwaita-theme/commit/a509a0bf7b85ecb37a9623af3a0f15afc7564172.

Example:
```bash
make install GNOME=44.0
```

**Comment by dipunm** [comment]
I am using arch Linux, is the recommendation to manually install instead of installing via the AUR? I am using gnome-shell 1:44.2-1

**Comment by akiirui** [comment]
Try to update this package to the latest from AUR.

**Comment by akiirui** [comment]
It works fine for me on Arch Linux with GNOME 44.2

![Screenshot from 2023-06-08 00-31-06](https://github.com/akiirui/akwaita-theme/assets/3736910/f860884f-3390-4799-8f47-afde82cc05bc)

**Comment by dipunm** [comment]
:thinking: I have this version:
```
~ ⟩ yay -Qi akwaita-theme-git
Name            : akwaita-theme-git
Version         : 44.2.r2.g38c55f4-1
```

Yet I still have this issue, I rebooted after installing the update.

**Comment by dipunm** [comment]
Let me test some extensions

**Comment by dipunm** [comment]
I turned off all extensions except `user-themes` and still have this issue unfortunately.

**Comment by dipunm** [comment]
Looks fine on the login screen though: 
![image](https://github.com/akiirui/akwaita-theme/assets/5099980/49a255e8-b7aa-4d67-b526-2eacfcb3dfde)

**Comment by akiirui** [comment]
Try to test the default shell theme？
because this theme based on it.

**Comment by dipunm** [comment]
Default theme looks fine but:
- text is bigger in titlebar
- no translucency in titlebar

**Comment by dipunm** [comment]
I will try to purge and re-install it

**Comment by akiirui** [comment]
Try turn off all extensions exclude user-theme, and restart gnome-shell.

For Xorg: Alt+F2 , r, Enter
For Wayland: logout

**Comment by dipunm** [comment]
Okay, I think I had some older files in my `.local/share/themes` folder. After removing that and re-installing, all is well again. Sorry and thankyou.

**Comment by akiirui** [comment]
Okay, This is something I didn't expect. 🤣🤣🤣
